CREAM = "#F5EFE6"
BEIGE = "#E8DFCA"
PASTEL = "#AEBDCA"
BLUE = "#7895B2"
FONT_NAME = "Courier"
TITLE = "Typing Speed Tester"
GREEN = "green"
RED = "red"

WORDS_IN_ROW = 6
ROWS_OF_WORDS = 3
TIMER_LENGTH = 60
